version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: anshul
      MYSQL_PASSWORD: anshul
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8333:8333"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - .:/app
